<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8287b23e-30a2-4d32-80e1-49c2ddf52e88}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
		
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_ADS_1();
P_Time();
P_History();
P_History_New();
P_UserManagment();
P_Recipebackup();
P_Gauge_Measures();
P_ADS_Gauge();
P_ADS_Err();
P_Error_Handling();


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>